language: node_js
node_js:
  - "5.5"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - npm install
  - bower install
  - npm run build
  - npm run test

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - s.rameshkrishnan@gmail.com
